import { join } from "node:path";
import type { RoundtableConfig } from "pi-roundtable";
import { sandbox } from "../src/index.ts";

const home = process.env.HOME;
if (!home) throw new Error("HOME is required");

/** Merge these plugins into the configuration generated by pi-roundtable init. */
export const sandboxConfig = {
	plugins: [
		sandbox({
			image: "pi-roundtable-sandbox:local",
			runRoot: "/tmp/roundtable-sandbox-run",
			workspaceRoot: join(home, ".local/share/roundtable-sandbox/workspaces"),
			stateFile: join(
				home,
				".local/share/roundtable-sandbox/state/channels.json",
			),
			provider: "openai",
			model: "operator-selected-model",
			modelUrl: "https://api.openai.com/v1/chat/completions",
			tools: [
				{
					name: "clock",
					description: "Read the current UTC time",
					parameters: {
						type: "object",
						properties: {},
						additionalProperties: false,
					},
					run: () => new Date().toISOString(),
				},
			],
		}),
	],
} satisfies Pick<RoundtableConfig, "plugins">;
